version: "3"

services:

  docker-playwright:
    image: mcr.microsoft.com/playwright:v1.42.1-focal
    container_name: docker-playwright
    volumes:
      - ./:/app
    command: bash -c "cd app && npx playwright test"
