version: "3"

services:

  docker-playwright:
    image: mcr.microsoft.com/playwright:bionic
    container_name: docker-playwright
    volumes: 
      - ./:/app
    command: bash -c "cd app
      && ls
      && npm run test:all"
